INSERT INTO DB_BOOKS.AUTHORS (NAME, AUTHORID) VALUES ('author1', 1);
INSERT INTO DB_BOOKS.AUTHORS (NAME, AUTHORID) VALUES ('author2', 2);
INSERT INTO DB_BOOKS.AUTHORS (NAME, AUTHORID) VALUES ('author3', 3);
INSERT INTO DB_BOOKS.AUTHORS (NAME, AUTHORID) VALUES ('coolAuthor', 4);

INSERT INTO DB_BOOKS.PUBLISHING (NAME, PUBLISHINGID) VALUES ('pub1', 1);
INSERT INTO DB_BOOKS.PUBLISHING (NAME, PUBLISHINGID) VALUES ('pub2', 2);
INSERT INTO DB_BOOKS.PUBLISHING (NAME, PUBLISHINGID) VALUES ('badPublishing', 3);

INSERT INTO DB_BOOKS.BOOKS (TITLE, AUTHOR, PUBLISHING, YEAR, COST, BOOKID) VALUES ('ssBook', 1, 1, 2019, 100.00, 2);
INSERT INTO DB_BOOKS.BOOKS (TITLE, AUTHOR, PUBLISHING, YEAR, COST, BOOKID) VALUES ('book3', 2, 2, 2019, 2220.12, 3);
INSERT INTO DB_BOOKS.BOOKS (TITLE, AUTHOR, PUBLISHING, YEAR, COST, BOOKID) VALUES ('book4', 2, 2, 2012, 2220.12, 4);
INSERT INTO DB_BOOKS.BOOKS (TITLE, AUTHOR, PUBLISHING, YEAR, COST, BOOKID) VALUES ('testBoook', 3, 2, 1999, 12.00, 5);
INSERT INTO DB_BOOKS.BOOKS (TITLE, AUTHOR, PUBLISHING, YEAR, COST, BOOKID) VALUES ('tester', 2, 1, 2019, 0.00, 7);
INSERT INTO DB_BOOKS.BOOKS (TITLE, AUTHOR, PUBLISHING, YEAR, COST, BOOKID) VALUES ('testerBoOok', 1, 1, 2002, 444.00, 11);
INSERT INTO DB_BOOKS.BOOKS (TITLE, AUTHOR, PUBLISHING, YEAR, COST, BOOKID) VALUES ('kkkBook', 4, 1, 1992, 444.00, 12);
INSERT INTO DB_BOOKS.BOOKS (TITLE, AUTHOR, PUBLISHING, YEAR, COST, BOOKID) VALUES ('bigBook!', 4, 3, 1873, 202020.00, 13);
